name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: build
      run: ./buildscripts/build.ps1 quick-deploy
      shell: powershell
      
    - name: Build Artifacts - zip
      uses: actions/upload-artifact@v2.2.4
      with:
        name: zip
        path: './BuildArtifacts/Boxstarter.*.zip'

    - name: Build Artifacts - nupkg
      uses: actions/upload-artifact@v2.2.4
      with:
        name: nupkg
        path: './BuildArtifacts/Boxstarter.*.nupkg'
